# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fce < Formula
  desc "FreeCustom.Email CLI — Manage disposable inboxes from your terminal."
  homepage "https://github.com/DishIs/fce-cli"
  version "0.1.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.12/fce_0.1.12_darwin_amd64.tar.gz"
      sha256 "609a33f155e5af282b2ae88ace1d3b63321bc684b0c328102e7147ca1abbfdec"

      define_method(:install) do
        bin.install "fce"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.12/fce_0.1.12_darwin_arm64.tar.gz"
      sha256 "c64fa6799aa8101de8663be785cd5d8bb38ae6475d0cdb0b2ade2de4845c60ca"

      define_method(:install) do
        bin.install "fce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.12/fce_0.1.12_linux_amd64.tar.gz"
      sha256 "540adafad236e65538859041fe5434a11fbc9ea56d790c0e69397a46779a25f4"
      define_method(:install) do
        bin.install "fce"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.12/fce_0.1.12_linux_arm64.tar.gz"
      sha256 "fad007ef7ec548381bc77e4bdd7ba11e5b78ca11bbbe49f46ff2985c88a2a020"
      define_method(:install) do
        bin.install "fce"
      end
    end
  end
end
