# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fce < Formula
  desc "FreeCustom.Email CLI — Manage disposable inboxes from your terminal."
  homepage "https://github.com/DishIs/fce-cli"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.8/fce_0.1.8_darwin_amd64.tar.gz"
      sha256 "3f2e22751c14a6c4011080d288da6f03605c17ccaf0449fdcc84a1b9c618b901"

      define_method(:install) do
        bin.install "fce"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.8/fce_0.1.8_darwin_arm64.tar.gz"
      sha256 "251dadcdf6ae02c3134e65b76b9d55302a3e5054a434500f8e9bfda678ed6e90"

      define_method(:install) do
        bin.install "fce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.8/fce_0.1.8_linux_amd64.tar.gz"
      sha256 "9546a2d9b61b60732156573e839712d8c1bbed89ef96fda290f5f417fd5e4999"
      define_method(:install) do
        bin.install "fce"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.8/fce_0.1.8_linux_arm64.tar.gz"
      sha256 "98364b49a2e05779dd4a4a9c424ce713360fa12eb08cf8bfd2a294bd825ecf1d"
      define_method(:install) do
        bin.install "fce"
      end
    end
  end
end
