# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fce < Formula
  desc "FreeCustom.Email CLI — Manage disposable inboxes from your terminal."
  homepage "https://github.com/DishIs/fce-cli"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.7/fce_0.1.7_darwin_amd64.tar.gz"
      sha256 "26bc83576cddb95b2a33b7b1a3308914e074dfb6964879154b8d558a9f193e27"

      define_method(:install) do
        bin.install "fce"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.7/fce_0.1.7_darwin_arm64.tar.gz"
      sha256 "9a279f0c62d416f127c50f083acbc643139119a2b74a4c4e999e0f550667c1f0"

      define_method(:install) do
        bin.install "fce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.7/fce_0.1.7_linux_amd64.tar.gz"
      sha256 "ef4fd44a2a3ba0d8c589fd7845d56e459782183a3b8465e2ff7018d7fd18bb89"
      define_method(:install) do
        bin.install "fce"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DishIs/fce-cli/releases/download/v0.1.7/fce_0.1.7_linux_arm64.tar.gz"
      sha256 "875d25bec2a152ae4dc30f681e56e55bf87f4ebaa4ceee976ffc1e0522cb35ca"
      define_method(:install) do
        bin.install "fce"
      end
    end
  end
end
